### ISSUE TITLE
How Can I pack the war into the nar package?

### ISSUE THREAD

**Issue by BennetWang** [sponiro/gradle-nar-plugin#1]
How Can I pack the war into the nar package?

**Comment by sponiro** [comment]
Your usecase sounds unusual. I don't think that you should put a war file into a nar file. Nar files are more closely related to jars. War files are used to deploy web applications. To be more specific you have to provide more context.

**Comment by BennetWang** [comment]
I just want to add the feature of the advanced UI.This is a custom java web.

**Comment by sponiro** [comment]
Sorry, I have no clue what you are talking about. You have to be more specific. But I think you mistake this software with something entirely different.

**Comment by BennetWang** [comment]
I Want add the feature just like 
![image](https://cloud.githubusercontent.com/assets/8628895/19631299/21716338-99cd-11e6-9d14-de1267883333.png)

**Comment by sponiro** [comment]
This plugin is not a plugin for nifi directly. It is a plugin for the gradle build system to help build plugins for Apache NiFi.
