### ISSUE TITLE
The implementation configuration for dependencies is not included in bundled-dependencies

### ISSUE THREAD

**Issue by Mark-Bank** [sponiro/gradle-nar-plugin#4]
A project with dependencies under the `implementation` configuration aren't included in the project's nar. I'll dig into this more in a day or two (not the most familiar with gradle plugin development), but I expect adding 'project.configurations.implementation' to the [array assigned here](https://github.com/sponiro/gradle-nar-plugin/blob/master/src/main/groovy/de/fanero/gradle/plugin/nar/NarPlugin.groovy#L50) would include them.

... Actually, gradle was displeased when I tried simply hacking that into my project, but `project.configurations.runtimeClasspath` did work. I'll sniff around some more and probably put out a PR.

**Comment by sponiro** [comment]
This is because gradle changed over time and this plugin did not receive updates to keep up. Changing this behaviour would be a breaking change so a new version would be necessary.

**Comment by sponiro** [comment]
Thanks to @kaHaleMaKai the plugin is compatible with Gradle 6 now. Try again, please.
