### ISSUE TITLE
Plugin not packaging arbitrary files under META-INF/services into .nar

### ISSUE THREAD

**Issue by abhilashmandaliya** [sponiro/gradle-nar-plugin#5]
Hi
I am developing an apache pulsar connector where they require `pulsar-io.yaml` file to be present under `src/main/resources/META-INF/services`. I have that file present in the described location but when I package it in nar file using this plugin, it doesn't get added under `META-INF/services`. The `services` directory itself is not getting created in nar file. `META-INF` directory only has `MANIFEST.MF`  and `bundled-dependencies`

**Comment by abhilashmandaliya** [comment]
even org.apache.nifi.processor.Processor file is also not appearing in .nar file

**Comment by sponiro** [comment]
The created nar file contains the jar files inside the META-INF/bundled-dependencies folder. Inside this folder you can find your own jar which in turn contains another META-INF with your files.

**Comment by abhilashmandaliya** [comment]
The below trick helped me as the plugin uses jar packaging under the hood:

```
val nar: de.fanero.gradle.plugin.nar.Nar by tasks
nar.apply {
    from("./src/main/resources") {
        include("META-INF/services/pulsar-io.yaml")
    }
}
```

**Comment by slominskir** [comment]
Thanks for the work-around.   I wonder why this is required though?   Why does this plugin work differently than the maven NiFi plugin?   The pulsar-io.yaml file is actually in two places after the fix as the Gradle NiFi plugin sticks the resources inside the main jar file META-INF.

P.S. I'm using Groovy version of build.gradle so the syntax was:

```
nar {
     from("./src/main/resources") {
        include("META-INF/services/pulsar-io.yaml")
    }
}
```
